---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: coredns-etcd
  name: coredns-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: coredns-etcd
  template:
    metadata:
      labels:
        k8s-app: coredns-etcd
    spec:
      volumes:
        - name: certs
          secret:
            secretName: etcd-server
      containers:
      - command:
        - /usr/local/bin/etcd
        - --name
        - coredns-etcd
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://coredns-etcd:2379
        - --initial-cluster-state
        - new
        - -cert-file=/var/lib/etcd/certs/tls.crt
        - -key-file=/var/lib/etcd/certs/tls.key
        image: quay.io/coreos/etcd:v3.1.0
        name: coredns-etcd
        volumeMounts:
          - name: certs
            mountPath: /var/lib/etcd/certs
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-etcd
  labels:
    k8s-app: coredns-etcd
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "coredns-etcd"
spec:
  selector:
    k8s-app: coredns-etcd
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380

